// DB 마이그레이션 버전 관리 모듈
// AUTO-GENERATED by scripts/generate-migrations.ts. Do not edit by hand.
// Source of truth: supabase/migrations/001_*.sql
// 버전 체계: migration.version = 해당 마이그레이션이 추가된 package.json 버전과 동일
// 향후 마이그레이션 추가 시 SQL 끝에 db_schema_version 업데이트 구문 포함 필요

import packageJson from "../../package.json";

// 현재 앱 release 버전 (package.json 기준)
export const APP_VERSION: string = packageJson.version;

export interface Migration {
    version: string;
    title: string;
    feature: string;
    sql: string;
    sqliteSql?: string;
    manual?: string;
}

// a < b → -1 | a === b → 0 | a > b → 1
export function compareVersions(a: string, b: string): number {
    const pa = a.split(".").map(Number);
    const pb = b.split(".").map(Number);
    for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
        const diff = (pa[i] ?? 0) - (pb[i] ?? 0);
        if (diff !== 0) return diff < 0 ? -1 : 1;
    }
    return 0;
}

// dbVersion보다 높은 버전의 마이그레이션만 반환 (오름차순)
export function getPendingMigrations(dbVersion: string): Migration[] {
    return [...MIGRATIONS]
        .filter((m) => compareVersions(m.version, dbVersion) > 0)
        .sort((a, b) => compareVersions(a.version, b.version));
}

export const MIGRATIONS: Migration[] = [
    {
        version: "0.5.2",
        title: "tags.color 컬럼 추가",
        feature: "태그 색상 (oklch 컬러 피커)",
        sql: `ALTER TABLE tags
  ADD COLUMN IF NOT EXISTS color text;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.5.2"')
ON CONFLICT (key) DO UPDATE SET value = '"0.5.2"';`,
    },
    {
        version: "0.5.3",
        title: "posts SEO 메타 컬럼 추가",
        feature: "포스트 SEO (meta_title, meta_description, og_image)",
        sql: `ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS meta_title       text,
  ADD COLUMN IF NOT EXISTS meta_description text,
  ADD COLUMN IF NOT EXISTS og_image         text;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.5.3"')
ON CONFLICT (key) DO UPDATE SET value = '"0.5.3"';`,
    },
    {
        version: "0.5.4",
        title: "site_config 테이블 생성",
        feature: "사이트 설정 (색상 스킴, TOC 스타일 등)",
        sql: `CREATE TABLE IF NOT EXISTS site_config (
  key   text primary key,
  value jsonb not null
);

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.5.4"')
ON CONFLICT (key) DO UPDATE SET value = '"0.5.4"';`,
    },
    {
        version: "0.5.5",
        title: "resume_data 테이블 생성",
        feature: "이력서 관리 (언어별 데이터)",
        sql: `CREATE TABLE IF NOT EXISTS resume_data (
  id         uuid        primary key default gen_random_uuid(),
  lang       text        not null default 'ko',
  data       jsonb       not null,
  updated_at timestamptz not null default now(),
  unique(lang)
);

INSERT INTO resume_data (lang, data)
VALUES ('ko', '{}'::jsonb)
ON CONFLICT (lang) DO NOTHING;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.5.5"')
ON CONFLICT (key) DO UPDATE SET value = '"0.5.5"';`,
    },
    {
        version: "0.5.6",
        title: "posts.category 컬럼 추가",
        feature: "포스트 카테고리",
        sql: `ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS category text;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.5.6"')
ON CONFLICT (key) DO UPDATE SET value = '"0.5.6"';`,
    },
    {
        version: "0.6.2",
        title: "books 테이블 생성",
        feature: "도서 리뷰 (포트폴리오 연관 도서, books 상세 페이지)",
        sql: `CREATE TABLE IF NOT EXISTS books (
  id               uuid     primary key default gen_random_uuid(),
  slug             text     unique not null,
  title            text     not null,
  author           text,
  cover_url        text,
  description      text,
  content          text     not null default '',
  rating           smallint check (rating >= 1 and rating <= 5),
  tags             text[]   not null default '{}',
  job_field        text[]   not null default '{}',
  published        boolean  not null default false,
  featured         boolean  not null default false,
  order_idx        integer  not null default 0,
  data             jsonb    not null default '{}',
  meta_title       text,
  meta_description text,
  og_image         text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

ALTER TABLE books ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'books'
      AND policyname IN ('books_public_read', 'Public read published books')
  ) THEN
    CREATE POLICY "books_public_read"
      ON books FOR SELECT USING (published = true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'books'
      AND policyname IN ('books_auth_all', 'Authenticated full access')
  ) THEN
    CREATE POLICY "books_auth_all"
      ON books FOR ALL
      USING (auth.role() = 'authenticated')
      WITH CHECK (auth.role() = 'authenticated');
  END IF;
END $$;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.6.2"')
ON CONFLICT (key) DO UPDATE SET value = '"0.6.2"';`,
    },
    {
        version: "0.6.17",
        title: "resume_data.data → meta 구조로 이모지 설정 이전",
        feature:
            "이력서 섹션별 이모지 토글 (sectionLabels, showEmojis → meta 하위)",
        sql: `UPDATE resume_data
SET data = (data - 'sectionLabels' - 'showEmojis') ||
    jsonb_build_object(
        'meta',
        COALESCE(data->'meta', '{}'::jsonb) ||
        jsonb_build_object(
            'sectionLabels', COALESCE(data->'sectionLabels', '{}'::jsonb),
            'showEmojis',    COALESCE(data->'showEmojis',    '{}'::jsonb)
        )
    )
WHERE lang = 'ko';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.6.17"')
ON CONFLICT (key) DO UPDATE SET value = '"0.6.17"';`,
    },
    {
        version: "0.6.18",
        title: "resume_data 섹션별 emoji/showEmoji nested 구조로 이전",
        feature:
            "이력서 섹션 이모지 설정 per-section 중첩 구조 (ResumeSection<T>)",
        sql: `UPDATE resume_data
SET data = COALESCE(
  (
    SELECT jsonb_object_agg(
      section_key,
      CASE
        WHEN section_key = 'basics' THEN section_val
        WHEN jsonb_typeof(section_val) = 'array' THEN
          jsonb_build_object(
            'emoji',     COALESCE(data->'meta'->'sectionLabels'->section_key, '"✔️"'),
            'showEmoji', COALESCE(data->'meta'->'showEmojis'->section_key, 'false'),
            'entries',   section_val
          )
        ELSE section_val
      END
    )
    FROM jsonb_each(data - 'meta') AS t(section_key, section_val)
  ),
  '{}'::jsonb
)
WHERE lang = 'ko';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.6.18"')
ON CONFLICT (key) DO UPDATE SET value = '"0.6.18"';`,
    },
    {
        version: "0.6.20",
        title: "ai_agent_tokens 테이블 생성",
        feature: "MCP Agent API 토큰 인증",
        sql: `CREATE TABLE IF NOT EXISTS ai_agent_tokens (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  token_hash     TEXT        NOT NULL UNIQUE,
  label          TEXT        NOT NULL,
  duration_min   INTEGER     NOT NULL,
  expires_at     TIMESTAMPTZ NOT NULL,
  revoked        BOOLEAN     NOT NULL DEFAULT FALSE,
  last_used_at   TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE ai_agent_tokens ENABLE ROW LEVEL SECURITY;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.6.20"')
ON CONFLICT (key) DO UPDATE SET value = '"0.6.20"';`,
    },
    {
        version: "0.8.3",
        title: "에디터 상태 보존 테이블",
        feature: "editor_states",
        sql: `CREATE TABLE IF NOT EXISTS editor_states (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type  TEXT        NOT NULL,
    entity_slug  TEXT        NOT NULL,
    label        TEXT        NOT NULL,
    content      TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_editor_states_entity
    ON editor_states (entity_type, entity_slug, created_at DESC);

ALTER TABLE editor_states ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'editor_states_admin_all'
  ) THEN
    CREATE POLICY editor_states_admin_all ON editor_states
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.8.3"')
ON CONFLICT (key) DO UPDATE SET value = '"0.8.3"';`,
    },
    {
        version: "0.10.6",
        title: "랜딩 히어로 데이터 DB 시딩",
        feature: "about_data에 valuePillars + coreCompetencies 시딩",
        sql: `UPDATE about_data
SET data = data || '{
  "valuePillars": [
    {"label": "Pillar 1", "sub": "Sub 1", "description": "Admin에서 Value Pillar를 입력하세요"},
    {"label": "Pillar 2", "sub": "Sub 2", "description": "Admin에서 Value Pillar를 입력하세요"},
    {"label": "Pillar 3", "sub": "Sub 3", "description": "Admin에서 Value Pillar를 입력하세요"}
  ],
  "coreCompetencies": [
    {"title": "Value 1", "description": "Admin에서 Core Compentency를 입력하세요"},
    {"title": "Value 2", "description": "Admin에서 Core Compentency를 입력하세요"},
    {"title": "Value 3", "description": "Admin에서 Core Compentency를 입력하세요"}
  ]
}'::jsonb
WHERE NOT (data ? 'valuePillars');

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.10.6"')
ON CONFLICT (key) DO UPDATE SET value = '"0.10.6"';`,
    },
    {
        version: "0.10.18",
        title: "Storage 파일 목록 정책 보안 강화",
        feature: "images bucket SELECT 정책: public → authenticated only",
        manual: "storage.objects 테이블은 supabase_storage_admin 소유 — DDL 정책 변경은 Supabase Dashboard SQL Editor에서만 실행 가능",
        sql: `DROP POLICY IF EXISTS images_public_read ON storage.objects;

CREATE POLICY images_authenticated_select ON storage.objects
  FOR SELECT
  TO authenticated
  USING (bucket_id = 'images');

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.10.18"')
ON CONFLICT (key) DO UPDATE SET value = '"0.10.18"';`,
    },
    {
        version: "0.10.19",
        title: "Storage UPDATE/DELETE 정책 추가",
        feature: "images bucket에셋 이전(move) + 삭제(remove) 권한",
        manual: "storage.objects DDL 정책 — Supabase Dashboard SQL Editor에서 실행",
        sql: `CREATE POLICY images_authenticated_update ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (bucket_id = 'images');

CREATE POLICY images_authenticated_delete ON storage.objects
  FOR DELETE
  TO authenticated
  USING (bucket_id = 'images');

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.10.19"')
ON CONFLICT (key) DO UPDATE SET value = '"0.10.19"';`,
    },
    {
        version: "0.11.20",
        title: "about_data JSONB 키 이름 변경: coreValues → coreCompetencies",
        feature: "핵심역량 편집 UI를 ResumePanel로 이동, DB JSONB 키 일치",
        sql: `UPDATE about_data
SET data = jsonb_set(
    data - 'coreValues',
    '{coreCompetencies}',
    COALESCE(data->'coreValues', '[]'::jsonb)
)
WHERE data ? 'coreValues';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.11.20"')
ON CONFLICT (key) DO UPDATE SET value = '"0.11.20"';`,
    },
    {
        version: "0.11.21",
        title: "coreCompetencies 이동: about_data → resume_data",
        feature: "핵심역량 데이터를 이력서 테이블로 통합",
        sql: `UPDATE resume_data
SET data = data || jsonb_build_object(
    'coreCompetencies',
    COALESCE(
        (SELECT data->'coreCompetencies' FROM about_data LIMIT 1),
        '[]'::jsonb
    )
)
WHERE lang = 'ko'
  AND NOT (data ? 'coreCompetencies');

UPDATE about_data
SET data = data - 'coreCompetencies'
WHERE data ? 'coreCompetencies';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.11.21"')
ON CONFLICT (key) DO UPDATE SET value = '"0.11.21"';`,
    },
    {
        version: "0.11.68",
        title: "DB Snapshot 테이블 전환",
        feature: "database_snapshots 추가 + content_snapshots 제거",
        sql: `DROP TABLE IF EXISTS content_snapshots;
DROP FUNCTION IF EXISTS prune_snapshots();

CREATE TABLE IF NOT EXISTS database_snapshots (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    filename    TEXT        NOT NULL,
    data        JSONB       NOT NULL,
    table_names TEXT[]      NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_database_snapshots_created_at
    ON database_snapshots (created_at DESC);

ALTER TABLE database_snapshots ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'database_snapshots'
      AND policyname = 'database_snapshots_admin_all'
  ) THEN
    CREATE POLICY database_snapshots_admin_all ON database_snapshots
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

CREATE OR REPLACE FUNCTION create_database_snapshot()
RETURNS TABLE (
    id UUID,
    filename TEXT,
    table_names TEXT[],
    created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    snapshot_data JSONB := '{}'::jsonb;
    current_rows JSONB;
    current_table TEXT;
    included_tables TEXT[] := ARRAY[]::TEXT[];
    snapshot_time TIMESTAMPTZ := NOW();
    snapshot_filename TEXT;
BEGIN
    snapshot_filename := 'supabase-db-snapshot-' ||
        to_char(snapshot_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24-MI-SS"Z"') ||
        '.json';

    FOR current_table IN
        SELECT tablename
        FROM pg_catalog.pg_tables
        WHERE schemaname = 'public'
          AND tablename <> 'database_snapshots'
        ORDER BY tablename
    LOOP
        EXECUTE format(
            'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM public.%I t',
            current_table
        )
        INTO current_rows;

        snapshot_data := snapshot_data ||
            jsonb_build_object(current_table, current_rows);
        included_tables := array_append(included_tables, current_table);
    END LOOP;

    RETURN QUERY
    INSERT INTO database_snapshots (filename, data, table_names, created_at)
    VALUES (snapshot_filename, snapshot_data, included_tables, snapshot_time)
    RETURNING
        database_snapshots.id,
        database_snapshots.filename,
        database_snapshots.table_names,
        database_snapshots.created_at;
END;
$$;

REVOKE ALL ON FUNCTION create_database_snapshot() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_database_snapshot() TO service_role;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.11.68"')
ON CONFLICT (key) DO UPDATE SET value = '"0.11.68"';`,
    },
    {
        version: "0.11.72",
        title: "Gantt Chart archive 테이블 추가",
        feature: "CSV 기반 Gantt Chart archive 저장",
        sql: `CREATE TABLE IF NOT EXISTS gantt_chart_archives (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    title           TEXT        NOT NULL,
    source_filename TEXT        NOT NULL,
    csv_content     TEXT        NOT NULL,
    tasks           JSONB       NOT NULL DEFAULT '[]'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gantt_chart_archives_created_at
    ON gantt_chart_archives (created_at DESC);

ALTER TABLE gantt_chart_archives ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'gantt_chart_archives'
      AND policyname = 'gantt_chart_archives_admin_all'
  ) THEN
    CREATE POLICY gantt_chart_archives_admin_all ON gantt_chart_archives
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

DROP TRIGGER IF EXISTS trg_gantt_chart_archives_updated_at ON gantt_chart_archives;

CREATE TRIGGER trg_gantt_chart_archives_updated_at
    BEFORE UPDATE ON gantt_chart_archives
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.11.72"')
ON CONFLICT (key) DO UPDATE SET value = '"0.11.72"';`,
    },
    {
        version: "0.11.73",
        title: "Gantt Chart color scheme 컬럼 추가",
        feature: "Gantt Chart title + color scheme 수정과 preview 개선",
        sql: `ALTER TABLE gantt_chart_archives
  ADD COLUMN IF NOT EXISTS color_scheme TEXT NOT NULL DEFAULT 'emerald';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.11.73"')
ON CONFLICT (key) DO UPDATE SET value = '"0.11.73"';`,
    },
    {
        version: "0.11.74",
        title: "Gantt Chart bar style 컬럼 추가",
        feature: "Gantt Chart rounded/square bar style 설정",
        sql: `ALTER TABLE gantt_chart_archives
  ADD COLUMN IF NOT EXISTS bar_style TEXT NOT NULL DEFAULT 'rounded';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.11.74"')
ON CONFLICT (key) DO UPDATE SET value = '"0.11.74"';`,
    },
    {
        version: "0.11.81",
        title: "Gantt Chart category_colors 컬럼 추가",
        feature: "카테고리별 색상 커스터마이징 (category_colors JSONB)",
        sql: `ALTER TABLE gantt_chart_archives
  ADD COLUMN IF NOT EXISTS category_colors JSONB NOT NULL DEFAULT '{}';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.11.81"')
ON CONFLICT (key) DO UPDATE SET value = '"0.11.81"';`,
    },
    {
        version: "0.12.85",
        title: "admin_login_attempts 테이블 추가",
        feature: "관리자 로그인 rate limit 공유 저장소",
        sql: `CREATE TABLE IF NOT EXISTS admin_login_attempts (
    key_hash         TEXT        PRIMARY KEY,
    count            INTEGER     NOT NULL DEFAULT 0,
    first_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    blocked_until    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_admin_login_attempts_first_attempt_at
    ON admin_login_attempts (first_attempt_at);

ALTER TABLE admin_login_attempts ENABLE ROW LEVEL SECURITY;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.85"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.85"';`,
    },
    {
        version: "0.12.114",
        title: "영문 resume row 제거",
        feature: "resume_data를 ko 단일 source of truth로 정리",
        sql: `DELETE FROM resume_data
WHERE lang = 'en';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.114"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.114"';`,
        sqliteSql: `DELETE FROM refuge_rows
WHERE table_name = 'resume_data'
  AND identity = 'en';`,
    },
    {
        version: "0.12.148",
        title: "posts.tags GIN 인덱스 추가",
        feature:
            "TagsPanel 사용 포스트 preview의 태그 배열 containment 조회 최적화",
        sql: `CREATE INDEX IF NOT EXISTS idx_posts_tags_gin
ON posts USING GIN (tags);

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.148"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.148"';`,
    },
    {
        version: "0.12.149",
        title: "post_tags 정규화 조회 테이블 추가",
        feature:
            "TagsPanel 태그별 사용 포스트 preview를 tag_slug + pub_date 인덱스로 최적화",
        sql: `CREATE TABLE IF NOT EXISTS post_tags (
    post_id    UUID        NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_slug   TEXT        NOT NULL,
    pub_date   TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (post_id, tag_slug)
);

CREATE INDEX IF NOT EXISTS idx_post_tags_tag_pub_date
ON post_tags (tag_slug, pub_date DESC, post_id);

CREATE INDEX IF NOT EXISTS idx_posts_category_pub_date
ON posts (category, pub_date DESC);

INSERT INTO post_tags (post_id, tag_slug, pub_date)
SELECT
    posts.id,
    normalized_tags.tag_slug,
    posts.pub_date
FROM posts
CROSS JOIN LATERAL (
    SELECT DISTINCT btrim(tag) AS tag_slug
    FROM unnest(posts.tags) AS tag
    WHERE btrim(tag) <> ''
) AS normalized_tags
ON CONFLICT (post_id, tag_slug)
DO UPDATE SET pub_date = EXCLUDED.pub_date;

CREATE OR REPLACE FUNCTION sync_post_tags()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM post_tags WHERE post_id = NEW.id;

    INSERT INTO post_tags (post_id, tag_slug, pub_date)
    SELECT
        NEW.id,
        normalized_tags.tag_slug,
        NEW.pub_date
    FROM (
        SELECT DISTINCT btrim(tag) AS tag_slug
        FROM unnest(COALESCE(NEW.tags, '{}'::text[])) AS tag
        WHERE btrim(tag) <> ''
    ) AS normalized_tags
    ON CONFLICT (post_id, tag_slug)
    DO UPDATE SET pub_date = EXCLUDED.pub_date;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_post_tags ON posts;
CREATE TRIGGER trg_sync_post_tags
    AFTER INSERT OR UPDATE OF tags, pub_date ON posts
    FOR EACH ROW EXECUTE FUNCTION sync_post_tags();

ALTER TABLE post_tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "post_tags_public_read" ON post_tags;
CREATE POLICY "post_tags_public_read"
    ON post_tags FOR SELECT USING (
        EXISTS (
            SELECT 1
            FROM posts
            WHERE posts.id = post_tags.post_id
              AND posts.published = true
        )
    );

DROP POLICY IF EXISTS "post_tags_auth_all" ON post_tags;
CREATE POLICY "post_tags_auth_all"
    ON post_tags FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

CREATE OR REPLACE VIEW post_tag_counts
WITH (security_invoker = true) AS
SELECT
    tag_slug,
    COUNT(*)::int AS count
FROM post_tags
GROUP BY tag_slug;

CREATE OR REPLACE VIEW post_category_counts
WITH (security_invoker = true) AS
SELECT
    btrim(category) AS category,
    COUNT(*)::int AS count
FROM posts
WHERE category IS NOT NULL
  AND btrim(category) <> ''
GROUP BY btrim(category);

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.149"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.149"';`,
    },
    {
        version: "0.12.150",
        title: "post_categories registry 추가",
        feature: "TagsPanel에서 사용 포스트가 0개인 카테고리도 직접 생성/관리",
        sql: `CREATE TABLE IF NOT EXISTS post_categories (
    name        TEXT        PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_post_categories_created_at
ON post_categories (created_at DESC);

INSERT INTO post_categories (name)
SELECT DISTINCT btrim(category) AS name
FROM posts
WHERE category IS NOT NULL
  AND btrim(category) <> ''
ON CONFLICT (name) DO NOTHING;

ALTER TABLE post_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "post_categories_public_read" ON post_categories;
CREATE POLICY "post_categories_public_read"
    ON post_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "post_categories_auth_write" ON post_categories;
CREATE POLICY "post_categories_auth_write"
    ON post_categories FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

CREATE OR REPLACE VIEW post_category_counts
WITH (security_invoker = true) AS
WITH post_counts AS (
    SELECT
        btrim(category) AS category,
        COUNT(*)::int AS count
    FROM posts
    WHERE category IS NOT NULL
      AND btrim(category) <> ''
    GROUP BY btrim(category)
)
SELECT
    post_categories.name AS category,
    COALESCE(post_counts.count, 0)::int AS count
FROM post_categories
LEFT JOIN post_counts ON post_counts.category = post_categories.name
UNION
SELECT
    post_counts.category,
    post_counts.count
FROM post_counts
LEFT JOIN post_categories ON post_categories.name = post_counts.category
WHERE post_categories.name IS NULL;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.150"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.150"';`,
    },
    {
        version: "0.12.172",
        title: "post content chunk storage",
        feature: "긴 post content chunk 저장",
        sql: `CREATE TABLE IF NOT EXISTS post_content_revisions (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id      UUID        NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    content_hash TEXT        NOT NULL,
    content_size INTEGER     NOT NULL CHECK (content_size >= 0),
    chunk_size   INTEGER     NOT NULL CHECK (chunk_size > 0),
    chunk_count  INTEGER     NOT NULL CHECK (chunk_count > 0),
    active       BOOLEAN     NOT NULL DEFAULT FALSE,
    status       TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'committed')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    committed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS post_content_chunks (
    revision_id UUID    NOT NULL REFERENCES post_content_revisions(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
    content     TEXT    NOT NULL,
    checksum    TEXT    NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (revision_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_post_content_revisions_post_active
    ON post_content_revisions(post_id, active, committed_at DESC);

CREATE INDEX IF NOT EXISTS idx_post_content_chunks_revision_index
    ON post_content_chunks(revision_id, chunk_index);

ALTER TABLE post_content_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_content_chunks ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'post_content_revisions'
      AND policyname = 'post_content_revisions_public_read'
  ) THEN
    CREATE POLICY "post_content_revisions_public_read"
      ON post_content_revisions FOR SELECT USING (
        status = 'committed'
        AND active = true
        AND EXISTS (
          SELECT 1 FROM posts
          WHERE posts.id = post_content_revisions.post_id
            AND posts.published = true
        )
      );
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'post_content_revisions'
      AND policyname = 'post_content_revisions_auth_all'
  ) THEN
    CREATE POLICY "post_content_revisions_auth_all"
      ON post_content_revisions FOR ALL
      USING (auth.role() = 'authenticated')
      WITH CHECK (auth.role() = 'authenticated');
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'post_content_chunks'
      AND policyname = 'post_content_chunks_public_read'
  ) THEN
    CREATE POLICY "post_content_chunks_public_read"
      ON post_content_chunks FOR SELECT USING (
        EXISTS (
          SELECT 1
          FROM post_content_revisions r
          JOIN posts ON posts.id = r.post_id
          WHERE r.id = post_content_chunks.revision_id
            AND r.status = 'committed'
            AND r.active = true
            AND posts.published = true
        )
      );
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'post_content_chunks'
      AND policyname = 'post_content_chunks_auth_all'
  ) THEN
    CREATE POLICY "post_content_chunks_auth_all"
      ON post_content_chunks FOR ALL
      USING (auth.role() = 'authenticated')
      WITH CHECK (auth.role() = 'authenticated');
  END IF;
END $$;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.172"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.172"';`,
        sqliteSql: `DELETE FROM refuge_rows
WHERE table_name IN ('post_content_revisions', 'post_content_chunks');`,
    },
    {
        version: "0.12.189",
        title: "사이트 화면 모드 설정",
        feature: "공개 사이트 라이트·다크·시스템 화면 모드 정책",
        sql: `INSERT INTO site_config (key, value)
VALUES ('theme_mode', '"light"')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.189"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.189"';`,
        sqliteSql: `INSERT INTO refuge_rows (table_name, identity, row_json, updated_at)
VALUES ('site_config', 'theme_mode', '{"key":"theme_mode","value":"light"}', CURRENT_TIMESTAMP)
ON CONFLICT (table_name, identity) DO UPDATE SET
  row_json = excluded.row_json,
  updated_at = CURRENT_TIMESTAMP;`,
    },
    {
        version: "0.12.190",
        title: "기본 직무 분야 제거",
        feature: "직무 분야 공개 경로는 job_fields 등록 목록을 정본으로 사용",
        sql: `DELETE FROM public.site_config
WHERE key = 'job_field';

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.190"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.190"';`,
    },
    {
        version: "0.12.235",
        title: "직무 분야 배열 schema 보정",
        feature:
            "포스트와 포트폴리오의 다중 직무 분야 저장 및 containment 조회 지원",
        sql: `DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'posts'
          AND column_name = 'job_field'
          AND data_type = 'text'
    ) THEN
        ALTER TABLE public.posts
            ALTER COLUMN job_field TYPE TEXT[]
            USING CASE
                WHEN job_field IS NULL THEN NULL
                ELSE ARRAY[job_field]
            END;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'portfolio_items'
          AND column_name = 'job_field'
          AND data_type = 'text'
    ) THEN
        ALTER TABLE public.portfolio_items
            ALTER COLUMN job_field TYPE TEXT[]
            USING CASE
                WHEN job_field IS NULL THEN NULL
                ELSE ARRAY[job_field]
            END;
    END IF;
END $$;

INSERT INTO site_config (key, value)
VALUES ('db_schema_version', '"0.12.235"')
ON CONFLICT (key) DO UPDATE SET value = '"0.12.235"';`,
    },
];

// 현재 DB schema 버전 (가장 최근 migration 기준)
export const LATEST_SCHEMA_VERSION: string =
    MIGRATIONS.at(-1)?.version ?? APP_VERSION;
